on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  rss-issue-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: setup python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: install python dependency
        run: pip install -r requirements.txt
      - name: purge old feeds_report_result.txt
        run: rm -rf feeds_report_result.txt
      - name: generate feeds report
        run: python feeds_report.py
      - name: install node.js fs module
        run: npm install fs
      - name: create issue comment
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs')
            if (fs.existsSync('feeds_report_result.txt')) {
              github.rest.issues.createComment({
                issue_number: 1,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: fs.readFileSync('feeds_report_result.txt').toString()
              })
            }
      - name: update to repository
        run: |
          git config --global user.name 'metroish'
          git config --global user.email '8260430+metroish@users.noreply.github.com'
          git add .
          git commit -am "Updated by GitHub Action $(date)"
          git push origin main -f
