on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

jobs:
  rss-comment-purge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: list issue comments
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
              const comment_list = await github.rest.issues.listComments({
                issue_number: 1,
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
              for(key in comment_list) {
                if(key === 'data') {
                  for(idx in comment_list[key]) {
                    github.rest.issues.deleteComment({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      comment_id: comment_list[key][idx].id,
                    });
                  }
                }
              };

