on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

jobs:
  rss-comment-purge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: list issue comments
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
              const comment_list = github.rest.issues.listComments({
                issue_number: 1,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
              console.log(comment_list)
